/*
 * This source file was generated by the Gradle 'init' task
 */
package calculator;

import java.util.Scanner;

import main.java.calculator.Calculator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        

        // String test = "+";
        // System.out.println(test);
        // System.out.println(test == "+");

        // String test2 = new Scanner(System.in).next();
        // System.out.println(test);
        // System.out.println(test2.equals("+"));

        Calculator calc = new Calculator();
        calc.runAppUI();
        
        // float a = 5.7f;
        // float b = 0.4f;
        // System.out.println(a + b);
        // float c = new Scanner(System.in).nextFloat();
        // System.out.println(c);
        // float d = new Scanner(System.in).nextFloat();
        // System.out.println(d);
        // System.out.println(c+d);
        

    }
}
